# Site settings
title: Westin Wrzesinski Developer
email: westin.wrzesinski@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal Site for Westin Wrzesinski. Software Engineer residing in Chicago, Illinois.
  Graduated from Univeristy of Illinois at Chicago for Software Engineering.
  Focused on web app development using technologies including: JavaScript, NodeJS, MongoDB, Postgres, .Net, C#, Ruby, Rails.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: westeeze
github_username:  westeezy
linkedin_username: pub/westin-wrzesinski/44/106/4ba

# Build settings
markdown: kramdown
